from __future__ import annotations

"""
Hidden-Link Engine Adapter

Consumes the INFERRED relationships already persisted by the correlation
engine (routes/correlations.py) and surfaces each as a traceable finding. It
never invents links — confidence, component scores and reason codes come from
the stored inference, and every finding carries the supporting evidence refs.
"""
from orchestration.contracts import (
    HIDDEN_LINK,
    SEVERITY_HIGH,
    SEVERITY_MEDIUM,
    CaseContext,
    CognitiveResult,
    EngineSpec,
)
from graph.relationship_types import INFERRED

ENGINE_NAME = "HiddenLinkEngine"
ENGINE_VERSION = "2.0"


def _inferred(context: CaseContext) -> list[dict]:
    return [r for r in context.relationships if r.get("epistemic_status") == INFERRED]


def applies(context: CaseContext) -> bool:
    return bool(_inferred(context))


def run(context: CaseContext) -> list[CognitiveResult]:
    results: list[CognitiveResult] = []
    for rel in _inferred(context):
        confidence = float(rel.get("confidence") or 0.0)
        source = rel.get("source_value") or "?"
        target = rel.get("target_value") or "?"
        reason_codes = list(rel.get("reason_codes") or [])
        if "INFERRED_RELATIONSHIP" not in reason_codes:
            reason_codes.append("INFERRED_RELATIONSHIP")
        results.append(CognitiveResult(
            finding_type=HIDDEN_LINK,
            title=f"Hidden link — {source} ↔ {target}",
            description=(
                f"Inferred {rel.get('relationship_type', 'ASSOCIATED_WITH')} between "
                f"{source} and {target} at {round(confidence * 100)}% confidence."
            ),
            confidence=confidence if confidence else None,
            severity=SEVERITY_HIGH if confidence >= 0.7 else SEVERITY_MEDIUM,
            source_engine=rel.get("source_engine") or ENGINE_NAME,
            engine_version=rel.get("engine_version") or ENGINE_VERSION,
            entity_refs=[source, target],
            event_refs=list(rel.get("event_refs") or []),
            evidence_refs=list(rel.get("evidence_refs") or []),
            component_scores=dict(rel.get("component_scores") or {}),
            reason_codes=reason_codes,
            reasoning=(
                "Generated by cognitive link analysis — inferred, not directly "
                "observed. Reasons and supporting evidence are recorded."
            ),
            dedup_key=f"hidden_link:{rel.get('id')}",
        ))
    return results


SPEC = EngineSpec(
    name=ENGINE_NAME,
    version=ENGINE_VERSION,
    runner=run,
    description="Surfaces inferred (hidden) links as traceable findings.",
    applicability=applies,
    skip_reason="no_inferred_links",
)
