"""baseline_12_tables

Revision ID: 45cc32c7caff
Revises: 
Create Date: 2026-09-15 23:13:32.457376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45cc32c7caff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Cross-dialect type wrappers
JSON_TYPE = postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite")
ARRAY_TEXT = postgresql.ARRAY(sa.Text()).with_variant(sa.JSON(), "sqlite")


def upgrade() -> None:
    bind = op.get_bind()
    insp = sa.inspect(bind)
    existing_tables = set(insp.get_table_names())
    if "users" in existing_tables:
        # Pre-existing database (e.g. provisioned by init_db.sql); table creation skipped.
        # Delta migrations (e.g. existing_db_bridge) will reconcile schema differences.
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sandbox_firewall_rules',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('rule_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule_type', sa.String(length=32), nullable=True),
    sa.Column('target_cidr', sa.String(length=64), nullable=True),
    sa.Column('port_range', sa.String(length=128), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('protected', sa.Boolean(), nullable=True),
    sa.Column('owner_team', sa.String(length=64), nullable=True),
    sa.Column('last_modified_by', sa.String(length=128), nullable=True),
    sa.Column('last_modified_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('rank', sa.String(length=64), nullable=True),
    sa.Column('unit', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint("role IN ('constable','io','fiu_analyst','admin')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('entry_hash', sa.String(length=64), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.Text(), nullable=True),
    sa.Column('details_json', JSON_TYPE, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_hash')
    )
    op.create_table('cases',
    sa.Column('id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('case_number', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('crime_type', sa.String(length=64), nullable=True),
    sa.Column('fir_number', sa.String(length=64), nullable=True),
    sa.Column('police_station', sa.String(length=128), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assigned_officer_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=True),
    sa.Column('tags', ARRAY_TEXT, nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("priority IN ('high','medium','low')", name='ck_cases_priority'),
    sa.CheckConstraint("status IN ('open','in_progress','under_review','closed','on_hold')", name='ck_cases_status'),
    sa.ForeignKeyConstraint(['assigned_officer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    op.create_index('idx_cases_priority', 'cases', ['priority'], unique=False)
    op.create_index('idx_cases_status', 'cases', ['status'], unique=False)
    op.create_table('agent_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('triggered_by', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actions_json', JSON_TYPE, nullable=True),
    sa.CheckConstraint("status IN ('idle','investigating','analyzing','executing','blocked','awaiting_approval','completed','failed')", name='ck_agent_sessions_status'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_sessions_case_id', 'agent_sessions', ['case_id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('case_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('canonical_value', sa.String(length=512), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('node_metadata', JSON_TYPE, nullable=True),
    sa.Column('degree_centrality', sa.Float(), nullable=True),
    sa.Column('community_id', sa.Integer(), nullable=True),
    sa.Column('bridge_score', sa.Float(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_files',
    sa.Column('id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('case_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('original_name', sa.String(length=512), nullable=False),
    sa.Column('file_type', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('upload_status', sa.String(length=32), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('file_size_bytes IS NULL OR file_size_bytes >= 0', name='ck_evidence_size'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'sha256_hash', name='uq_evidence_case_sha256'),
    sa.UniqueConstraint('storage_path', name='uq_evidence_storage_path')
    )
    op.create_table('agent_actions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('details_json', JSON_TYPE, nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_actions_case_id', 'agent_actions', ['case_id'], unique=False)
    op.create_index('idx_agent_actions_session_id', 'agent_actions', ['session_id'], unique=False)
    op.create_table('agent_holds',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('case_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('authorization_boundary', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=True),
    sa.Column('affected_resource_json', JSON_TYPE, nullable=True),
    sa.Column('tool_params_json', JSON_TYPE, nullable=True),
    sa.Column('armoriq_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('approved_by', sa.String(length=128), nullable=True),
    sa.Column('rejected_by', sa.String(length=128), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('awaiting_approval','approved','rejected','expired')", name='ck_agent_holds_status'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_holds_case_id', 'agent_holds', ['case_id'], unique=False)
    op.create_index('idx_agent_holds_status', 'agent_holds', ['status'], unique=False)
    op.create_table('correlations',
    sa.Column('id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('case_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('entity_a_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('entity_b_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('link_type', sa.String(length=32), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('component_scores', JSON_TYPE, nullable=False),
    sa.Column('model_weights', JSON_TYPE, nullable=False),
    sa.Column('source_citations', JSON_TYPE, nullable=True),
    sa.Column('verified_by', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint("decision IN ('flagged','not_flagged')", name='ck_correlations_decision'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_a_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_b_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'entity_a_id', 'entity_b_id', name='uq_correlations_pair')
    )
    op.create_table('evidence_events',
    sa.Column('id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('case_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('evidence_file_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=True),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('source_line', sa.Integer(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('metadata', JSON_TYPE, nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_file_id'], ['evidence_files.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_mentions',
    sa.Column('id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('entity_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=True),
    sa.Column('evidence_event_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=True),
    sa.Column('raw_value', sa.String(length=512), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extractor', sa.String(length=32), nullable=True),
    sa.Column('span_start', sa.Integer(), nullable=True),
    sa.Column('span_end', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_event_id'], ['evidence_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entity_mentions')
    op.drop_table('evidence_events')
    op.drop_table('correlations')
    op.drop_index('idx_agent_holds_status', table_name='agent_holds')
    op.drop_index('idx_agent_holds_case_id', table_name='agent_holds')
    op.drop_table('agent_holds')
    op.drop_index('idx_agent_actions_session_id', table_name='agent_actions')
    op.drop_index('idx_agent_actions_case_id', table_name='agent_actions')
    op.drop_table('agent_actions')
    op.drop_table('evidence_files')
    op.drop_table('entities')
    op.drop_index('idx_agent_sessions_case_id', table_name='agent_sessions')
    op.drop_table('agent_sessions')
    op.drop_index('idx_cases_status', table_name='cases')
    op.drop_index('idx_cases_priority', table_name='cases')
    op.drop_table('cases')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_table('sandbox_firewall_rules')
    # ### end Alembic commands ###
