from __future__ import annotations

"""
NETRA 5.0 — Autonomous Copilot RAG Schemas
Defines canonical Pydantic V2 contracts across the entire Copilot RAG pipeline:
1. Ingress query & intent planning
2. Multi-modal retrieval units (Vector, Graph, SQL, Timeline)
3. RRF Fusion & context assembly
4. Semantic CRAG verification & statutory governance
5. Final investigator-facing egress response (100% frontend compatible)
"""

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


# ─────────────────────────────────────────────────────────────────────────────
# 1. Ingress & Query Planning Contracts
# ─────────────────────────────────────────────────────────────────────────────

class QueryIntentType(str, Enum):
    """Classified investigative query intent."""
    FACTUAL = "factual"            # Direct entity, transaction, or event question
    RELATIONAL = "relational"      # Connections, hidden links, mule layering rings
    TEMPORAL = "temporal"          # Sequence of events, crime timeline, replay
    STATUTORY = "statutory"        # Legal provisions, BSA S.63, BNSS S.105/106, BNS
    ADVERSARIAL = "adversarial"    # Red-team stress-test, defense challenge
    GENERAL = "general"            # Greeting, meta-case summary, or help


class CopilotQuery(BaseModel):
    """
    Ingress request payload matching frontend apiClient contract.
    Preserves exact field compatibility with legacy routes/copilot.py.
    """
    model_config = ConfigDict(extra="ignore")

    question: str = Field(..., min_length=1, description="Investigator prompt or query")
    top_k: int = Field(default=5, ge=1, le=50, description="Top K evidence items to retrieve")
    focus_entity: Optional[str] = Field(default=None, description="Optional canonical entity filter")
    require_statutory_audit: bool = Field(default=True, description="Run statutory compliance shield")


class QueryPlan(BaseModel):
    """Deconstructed query plan generated by query_planner.py."""
    model_config = ConfigDict(extra="ignore")

    original_query: str
    intent: QueryIntentType
    sub_queries: List[str] = Field(default_factory=list)
    target_modalities: List[str] = Field(default_factory=lambda: ["vector", "graph", "structured"])
    target_entities: List[str] = Field(default_factory=list)
    time_window_start: Optional[datetime] = None
    time_window_end: Optional[datetime] = None
    suggested_statutes: List[str] = Field(default_factory=list)


# ─────────────────────────────────────────────────────────────────────────────
# 2. Multi-Modal Retrieval Units
# ─────────────────────────────────────────────────────────────────────────────

class ModalityType(str, Enum):
    VECTOR = "vector"
    GRAPH = "graph"
    STRUCTURED = "structured"
    TIMELINE = "timeline"


class DocumentChunk(BaseModel):
    """Text chunk extracted from evidence files for vector embedding."""
    model_config = ConfigDict(extra="ignore")

    id: str
    case_id: str
    evidence_file_id: Optional[str] = None
    filename: str
    file_hash: Optional[str] = None
    chunk_index: int = 0
    text: str
    source_line: Optional[str] = None
    source_page: Optional[str] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)


class GraphNodeSnippet(BaseModel):
    """Entity node retrieved from the unified case graph."""
    model_config = ConfigDict(extra="ignore")

    entity_id: str
    canonical_value: str
    entity_type: str
    risk_score: float = 0.0
    bridge_score: float = 0.0
    community_id: Optional[int] = None


class GraphEdgeSnippet(BaseModel):
    """Relational edge retrieved from the unified case graph."""
    model_config = ConfigDict(extra="ignore")

    source_canonical: str
    target_canonical: str
    relationship_type: str
    confidence: float
    epistemic_status: str  # "OBSERVED" | "INFERRED"
    citations: List[Dict[str, Any]] = Field(default_factory=list)


class StructuredRecordSnippet(BaseModel):
    """An exact structured database record retrieved from PostgreSQL."""
    model_config = ConfigDict(extra="ignore")

    record_id: str
    table_name: str
    record_type: str  # "bank_txn" | "call" | "whatsapp_msg" | "network_log" | "location_timeline" | "entity" | "finding"
    timestamp: Optional[datetime] = None
    summary_text: str
    exact_payload: Dict[str, Any] = Field(default_factory=dict)
    source_file: Optional[str] = None
    source_line: Optional[str] = None
    source_page: Optional[str] = None
    confidence: float = 1.0


class StructuredRecordContext(BaseModel):
    """Container for all structured records retrieved for a query."""
    model_config = ConfigDict(extra="ignore")

    case_id: str
    records: List[StructuredRecordSnippet] = Field(default_factory=list)
    total_count: int = 0


class RetrievedItem(BaseModel):
    """Unified container for items retrieved from any individual modality."""
    model_config = ConfigDict(extra="ignore")

    id: str
    modality: ModalityType
    score: float
    text: str
    source_file: str
    source_line: Optional[str] = None
    source_page: Optional[str] = None
    raw_payload: Dict[str, Any] = Field(default_factory=dict)


# ─────────────────────────────────────────────────────────────────────────────
# 3. Fusion & Context Assembly Contracts
# ─────────────────────────────────────────────────────────────────────────────

class FusedItem(BaseModel):
    """Fused retrieval candidate ranked via Reciprocal Rank Fusion (RRF)."""
    model_config = ConfigDict(extra="ignore")

    id: str
    rank: int
    fused_score: float
    text: str
    source_file: str
    source_line: Optional[str] = None
    source_page: Optional[str] = None
    modalities: List[ModalityType] = Field(default_factory=list)
    raw_payload: Dict[str, Any] = Field(default_factory=dict)
    epistemic_status: Optional[str] = None
    citations: List[Dict[str, Any]] = Field(default_factory=list)
    rerank_score: Optional[float] = None
    final_score: Optional[float] = None


class CaseContextSnapshot(BaseModel):
    """Database ground-truth snapshot strictly bound to case_id."""
    model_config = ConfigDict(extra="ignore")

    case_id: str
    case_number: str
    title: str
    crime_type: Optional[str] = None
    status: str = "open"
    priority: str = "medium"
    total_evidence_files: int = 0
    total_entities: int = 0
    total_events: int = 0
    total_findings: int = 0
    evidence_files: List[str] = Field(default_factory=list)


class AssembledContext(BaseModel):
    """Final context payload passed to prompt_builder.py."""
    model_config = ConfigDict(extra="ignore")

    case_snapshot: CaseContextSnapshot
    fused_items: List[FusedItem] = Field(default_factory=list)
    graph_nodes: List[GraphNodeSnippet] = Field(default_factory=list)
    graph_edges: List[GraphEdgeSnippet] = Field(default_factory=list)
    structured_records: List[StructuredRecordSnippet] = Field(default_factory=list)
    statutory_context: Dict[str, Any] = Field(default_factory=dict)
    is_empty_case: bool = False


class GenerationPrompt(BaseModel):
    """Grounded prompt payload produced by prompt_builder.py for the generator."""
    model_config = ConfigDict(extra="ignore")

    system_prompt: str
    user_prompt: str
    query: str
    case_id: str
    estimated_tokens: int
    intent: Optional[str] = None
    is_empty_case: bool = False


GenerationRequest = GenerationPrompt


class GeneratedResponse(BaseModel):
    """Raw generation output produced by generator.py before claim verification."""
    model_config = ConfigDict(extra="ignore")

    text: str
    provider: str
    model: str
    used_fallback: bool
    latency_ms: Optional[float] = None


# ─────────────────────────────────────────────────────────────────────────────
# 4. Verification & Governance Contracts (Semantic CRAG Firewall)
# ─────────────────────────────────────────────────────────────────────────────

class SpanGrounding(BaseModel):
    """Fine-grained factual assertion grounding against case ground truth."""
    model_config = ConfigDict(extra="ignore")

    claim_type: str  # "amounts" | "phones" | "upis" | "accounts" | "ips" | "devices"
    raw_value: str
    normalized_value: str
    span_start: int
    span_end: int
    grounded: bool
    source_event_id: Optional[str] = None


class StatutoryAuditItem(BaseModel):
    """Statutory validation result under BSA 2023 / BNSS 2023 / IT Act."""
    model_config = ConfigDict(extra="ignore")

    section: str
    act: str
    status: str  # "in_force" | "pre_transition_act" | "struck_down" | "unknown_section"
    reason: Optional[str] = None
    replacement: Optional[str] = None


class Claim(BaseModel):
    """An individual extracted claim assessed for factual grounding against case evidence."""
    model_config = ConfigDict(extra="ignore")

    claim_id: str
    text: str
    claim_type: str = "factual"  # "amount" | "entity" | "relationship" | "finding" | "statutory" | "factual"
    is_verifiable: bool = True
    grounded: bool = False
    epistemic_violation: bool = False
    citations: List[str] = Field(default_factory=list)
    entities: List[str] = Field(default_factory=list)
    amounts: List[str] = Field(default_factory=list)
    dates: List[str] = Field(default_factory=list)
    supporting_item_ids: List[str] = Field(default_factory=list)
    supporting_citations: List[Dict[str, Any]] = Field(default_factory=list)
    reason: Optional[str] = None


class VerificationReport(BaseModel):
    """Post-generation claim verification and legal compliance critique result."""
    model_config = ConfigDict(extra="ignore")

    passed: bool
    total_claims: int = 0
    verifiable_claims: int = 0
    grounded_claims: int = 0
    unsupported_claims: int = 0
    grounded_claim_ratio: float = 1.0
    citation_count: int = 0
    valid_citation_count: int = 0
    invalid_citations: List[str] = Field(default_factory=list)
    epistemic_violations: int = 0
    abstained: bool = False
    claims: List[Claim] = Field(default_factory=list)
    case_id: Optional[str] = None
    repaired_text: Optional[str] = None
    warning: Optional[str] = None

    governance_verdict: str = "COMPLIANT"  # "COMPLIANT" | "NEEDS_REVIEW" | "GOVERNANCE_BLOCKED"
    governance_reasons: List[str] = Field(default_factory=list)
    statutory_violations: List[StatutoryAuditItem] = Field(default_factory=list)
    grounding_failures: List[Dict[str, Any]] = Field(default_factory=list)
    grounded_spans: List[SpanGrounding] = Field(default_factory=list)
    admissibility_disclaimer: str = (
        "NETRA produces evidence-grounded investigative intelligence drafts. "
        "Final legal admissibility remains with the authorized investigator and judicial process."
    )


ClaimVerificationReport = VerificationReport


class VerifiedResponse(BaseModel):
    """Final post-verification payload produced by claim_verifier.py."""
    model_config = ConfigDict(extra="ignore")

    text: str
    original_text: str
    passed: bool
    abstained: bool
    grounded_claim_ratio: float
    report: VerificationReport
    case_id: str
    mutation_proposals: List[Dict[str, Any]] = Field(default_factory=list)


# ─────────────────────────────────────────────────────────────────────────────
# 5. Egress & Response Contracts (100% Frontend TypeScript Compatible)
# ─────────────────────────────────────────────────────────────────────────────

class Citation(BaseModel):
    """
    Verified citation matching frontend Citation interface:
    export interface Citation { rank: number; file: string; line: string; page: string; text: string; verified: boolean; }
    """
    model_config = ConfigDict(extra="ignore")

    rank: int
    file: str
    line: str = "N/A"
    page: str = "N/A"
    text: str
    verified: bool = True
    evidence_id: Optional[str] = None
    entity_id: Optional[str] = None


class RetrievedSnippet(BaseModel):
    """
    Retrieved snippet matching frontend RetrievedSnippet interface:
    export interface RetrievedSnippet { id: string; rank: number; text: string; file: string; line: string; score: number; }
    """
    model_config = ConfigDict(extra="ignore")

    id: str
    rank: int
    text: str
    file: str
    line: str = "N/A"
    page: Optional[str] = "N/A"
    score: float = 0.0
    modality: Optional[str] = "vector"


class CopilotResponse(BaseModel):
    """
    Complete Copilot response matching frontend CopilotResponse interface:
    export interface CopilotResponse {
        answer: string;
        citations: Citation[];
        retrieved_snippets?: RetrievedSnippet[];
        model_used: string;
        is_generated?: boolean;
        abstained?: boolean;
        warning?: string | null;
    }
    """
    model_config = ConfigDict(extra="ignore", protected_namespaces=())

    answer: str
    citations: List[Citation] = Field(default_factory=list)
    retrieved_snippets: List[RetrievedSnippet] = Field(default_factory=list)
    model_used: str
    is_generated: bool = True
    abstained: bool = False
    warning: Optional[str] = None
    verification: Optional[Dict[str, Any]] = None
    query_plan: Optional[Dict[str, Any]] = None
    mutation_proposals: List[Dict[str, Any]] = Field(default_factory=list)
