from __future__ import annotations

"""
NETRA 5.0 — Forensic Vector Store (ChromaDB Integration)

Case-isolated vector storage and dense similarity retrieval:
1. Strict Case Boundary Isolation:
   - Separate Chroma collection per case: {prefix}_{sanitized_case_id}
   - Case ID validation (rejects directory traversal, spaces, illegal characters)
   - Dual-layer containment: isolated collection + metadata case_id filtering
   - Zero cross-case data leakage guaranteed
2. Provenance-Preserving Storage:
   - Stores DocumentChunk records with immutable forensic metadata (file_hash, file_id, line, page)
   - Sanitizes nested metadata to Chroma-supported primitive types (str, int, float, bool)
3. Normalized Similarity Scoring:
   - Converts raw Chroma distance (cosine / L2 / ip) into normalized similarity [0.0, 1.0]
4. Deduplication & Idempotence:
   - Chunk IDs generated by ForensicChunker act as primary keys in Chroma upsert
   - Re-indexing identical chunks replaces without accumulating duplicate records
"""

import os
import re
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Union

from chromadb import PersistentClient
from chromadb.api.models.Collection import Collection

from config import settings as app_settings
from .config import CopilotConfig, get_copilot_config
from .embeddings import EmbeddingService
from .schemas import DocumentChunk, ModalityType, RetrievedItem


# Case ID validation regex: alphanumeric, dashes, and underscores only
VALID_CASE_ID_RE = re.compile(r"^[a-zA-Z0-9_\-]+$")


class VectorStore:
    """
    Forensic vector storage manager providing strict case-isolated
    dense indexing and retrieval.
    """

    def __init__(
        self,
        config: Optional[CopilotConfig] = None,
        embedding_service: Optional[EmbeddingService] = None,
        persist_dir: Optional[str] = None,
    ):
        self.config = config or get_copilot_config()
        self.embedding_service = embedding_service or EmbeddingService(config=self.config)

        # Chroma storage path
        base_dir = persist_dir or getattr(app_settings, "chroma_persist_dir", "./artifacts/chroma_db")
        Path(base_dir).mkdir(parents=True, exist_ok=True)
        self.persist_dir = str(Path(base_dir).resolve())

        self._client = PersistentClient(path=self.persist_dir)

    # ─────────────────────────────────────────────────────────────────────────
    # Case Validation & Collection Resolution
    # ─────────────────────────────────────────────────────────────────────────

    def validate_case_id(self, case_id: str) -> str:
        """Validate and sanitize case identifier. Rejects illegal or traversal chars."""
        if not case_id or not isinstance(case_id, str):
            raise ValueError("case_id must be a non-empty string")

        clean_id = case_id.strip()
        if not VALID_CASE_ID_RE.match(clean_id) or ".." in clean_id or "/" in clean_id or "\\" in clean_id:
            raise ValueError(f"Invalid case_id format: '{case_id}'. Must be alphanumeric with dashes/underscores.")

        return clean_id

    def get_collection_name(self, case_id: str) -> str:
        """Derive safe, deterministic Chroma collection name for case."""
        clean_id = self.validate_case_id(case_id)
        # Chroma collection names: 3-63 chars, alphanumeric, starts/ends with alphanumeric
        sanitized = re.sub(r"[^a-zA-Z0-9_\-]", "_", clean_id)
        prefix = self.config.vector_collection_prefix or "netra_case"
        full_name = f"{prefix}_{sanitized}"[:63]
        return full_name

    def get_collection(self, case_id: str, create: bool = True) -> Optional[Collection]:
        """Retrieve or create case-isolated Chroma collection."""
        col_name = self.get_collection_name(case_id)
        distance_metric = self.config.vector_distance_metric or "cosine"

        if create:
            # Map distance metric to Chroma hnsw:space
            space = "cosine"
            if distance_metric in ("l2", "euclidean"):
                space = "l2"
            elif distance_metric in ("ip", "dot"):
                space = "ip"

            return self._client.get_or_create_collection(
                name=col_name,
                metadata={"hnsw:space": space, "case_id": case_id},
            )

        try:
            return self._client.get_collection(name=col_name)
        except Exception:
            return None

    # ─────────────────────────────────────────────────────────────────────────
    # Metadata Sanitization
    # ─────────────────────────────────────────────────────────────────────────

    def _sanitize_metadata(self, chunk: DocumentChunk) -> Dict[str, Union[str, int, float, bool]]:
        """Flatten and sanitize chunk metadata into Chroma-compatible primitive types."""
        clean_meta: Dict[str, Union[str, int, float, bool]] = {
            "case_id": str(chunk.case_id),
            "evidence_file_id": str(chunk.evidence_file_id or "unknown"),
            "file_hash": str(chunk.file_hash or "unknown"),
            "filename": str(chunk.filename),
            "chunk_index": int(chunk.chunk_index),
            "source_line": str(chunk.source_line or "1"),
            "source_page": str(chunk.source_page or "1"),
        }

        # Include custom metadata if primitives
        if chunk.metadata:
            for k, v in chunk.metadata.items():
                if isinstance(v, (str, int, float, bool)):
                    clean_meta[k] = v
                elif v is not None:
                    clean_meta[k] = str(v)

        return clean_meta

    # ─────────────────────────────────────────────────────────────────────────
    # Chunk Indexing & Upsert
    # ─────────────────────────────────────────────────────────────────────────

    def index_chunks(
        self,
        case_id: str,
        chunks: Sequence[DocumentChunk],
    ) -> int:
        """Alias for upsert_chunks. Embeds and stores chunks in the case collection."""
        return self.upsert_chunks(case_id, chunks)

    def upsert_chunks(
        self,
        case_id: str,
        chunks: Sequence[DocumentChunk],
        embeddings: Optional[Sequence[Sequence[float]]] = None,
    ) -> int:
        """
        Upsert document chunks into the case collection.
        Deduplicates by chunk.id.
        """
        if not chunks:
            return 0

        clean_case = self.validate_case_id(case_id)
        # Verify cross-case boundary invariant
        for chk in chunks:
            if chk.case_id != clean_case:
                raise ValueError(
                    f"Cross-case chunk contamination: chunk.case_id '{chk.case_id}' != target '{clean_case}'"
                )

        collection = self.get_collection(clean_case, create=True)

        # Generate embeddings if not provided
        if embeddings is None:
            chunk_vectors = self.embedding_service.embed_chunks(chunks)
            vectors = [vec for _, vec in chunk_vectors]
        else:
            vectors = [list(v) for v in embeddings]

        if len(vectors) != len(chunks):
            raise ValueError(f"Embeddings count ({len(vectors)}) != chunks count ({len(chunks)})")

        # Validate vector dimensions
        for v in vectors:
            if len(v) != self.embedding_service.dimension:
                raise ValueError(
                    f"Vector dimension mismatch: got {len(v)}, expected {self.embedding_service.dimension}"
                )

        ids = [c.id for c in chunks]
        documents = [c.text for c in chunks]
        metadatas = [self._sanitize_metadata(c) for c in chunks]

        collection.upsert(
            ids=ids,
            embeddings=vectors,
            documents=documents,
            metadatas=metadatas,
        )

        return len(chunks)

    # ─────────────────────────────────────────────────────────────────────────
    # Similarity Search
    # ─────────────────────────────────────────────────────────────────────────

    def search(
        self,
        case_id: str,
        query_vector: Sequence[float],
        top_k: Optional[int] = None,
        where: Optional[Dict[str, Any]] = None,
    ) -> List[RetrievedItem]:
        """
        Execute dense vector search strictly scoped to the case collection.
        Converts distance to normalized similarity score [0.0, 1.0].
        """
        if not query_vector:
            return []

        clean_case = self.validate_case_id(case_id)
        collection = self.get_collection(clean_case, create=False)
        if not collection:
            return []

        count = collection.count()
        if count == 0:
            return []

        k = top_k or self.config.default_top_k
        query_k = min(k, count)

        # Dimension check
        if len(query_vector) != self.embedding_service.dimension:
            raise ValueError(
                f"Query vector dimension mismatch: expected {self.embedding_service.dimension}, got {len(query_vector)}"
            )

        # Secondary containment filter
        query_where = {"case_id": clean_case}
        if where:
            query_where.update(where)

        try:
            results = collection.query(
                query_embeddings=[list(query_vector)],
                n_results=query_k,
                where=query_where,
                include=["documents", "metadatas", "distances"],
            )
        except Exception:
            return []

        retrieved_items: List[RetrievedItem] = []
        if not results or not results.get("ids") or len(results["ids"][0]) == 0:
            return []

        ids = results["ids"][0]
        docs = results.get("documents", [[]])[0]
        metas = results.get("metadatas", [[]])[0]
        distances = results.get("distances", [[]])[0]

        metric = (self.config.vector_distance_metric or "cosine").lower()

        for doc_id, doc_text, meta, dist in zip(ids, docs, metas, distances):
            # Assert tenant isolation strictly
            if meta.get("case_id") != clean_case:
                continue

            # Convert distance to normalized similarity score [0.0, 1.0]
            if metric == "cosine":
                # Cosine distance in Chroma: d = 1 - cosine_similarity ∈ [0, 2]
                score = max(0.0, min(1.0, 1.0 - float(dist)))
            elif metric in ("l2", "euclidean"):
                # L2 distance: similarity = 1 / (1 + d)
                score = 1.0 / (1.0 + max(0.0, float(dist)))
            else:
                score = max(0.0, min(1.0, 1.0 - float(dist)))

            retrieved_items.append(
                RetrievedItem(
                    id=doc_id,
                    modality=ModalityType.VECTOR,
                    score=round(score, 4),
                    text=doc_text,
                    source_file=meta.get("filename", "evidence"),
                    source_line=meta.get("source_line"),
                    source_page=meta.get("source_page"),
                    raw_payload=dict(meta),
                )
            )

        # Sort descending by normalized similarity score
        retrieved_items.sort(key=lambda item: item.score, reverse=True)
        return retrieved_items

    def search_text(
        self,
        case_id: str,
        query_text: str,
        top_k: Optional[int] = None,
        where: Optional[Dict[str, Any]] = None,
    ) -> List[RetrievedItem]:
        """High-level convenience method: embeds query_text and executes search."""
        if not query_text or not query_text.strip():
            return []

        query_vec = self.embedding_service.embed(query_text, case_id=case_id)
        return self.search(case_id, query_vec, top_k=top_k, where=where)

    # ─────────────────────────────────────────────────────────────────────────
    # Maintenance & Administration
    # ─────────────────────────────────────────────────────────────────────────

    def count(self, case_id: str) -> int:
        """Return total document count in the case collection."""
        clean_case = self.validate_case_id(case_id)
        collection = self.get_collection(clean_case, create=False)
        return collection.count() if collection else 0

    def delete_chunks(self, case_id: str, chunk_ids: Sequence[str]) -> None:
        """Delete specific chunk IDs from the case collection."""
        if not chunk_ids:
            return
        clean_case = self.validate_case_id(case_id)
        collection = self.get_collection(clean_case, create=False)
        if collection:
            collection.delete(ids=list(chunk_ids))

    def reset_case(self, case_id: str) -> None:
        """Permanently delete and purge the case collection."""
        clean_case = self.validate_case_id(case_id)
        col_name = self.get_collection_name(clean_case)
        try:
            self._client.delete_collection(name=col_name)
        except Exception:
            pass

    def list_case_collections(self) -> List[str]:
        """List all case collections managed by the vector store."""
        collections = self._client.list_collections()
        prefix = self.config.vector_collection_prefix or "netra_case"
        return [c.name for c in collections if c.name.startswith(prefix)]
